/**
 * v3 hand-curated additions — fills the gaps surfaced by the audit:
 * lake towns, beach/coastal staples, missing major cities, scenic byways,
 * mountain towns, and a few destination islands. Each entry is fully
 * populated (landscape / experiences / sceneryScore / scenicSignals).
 *
 * Merged into `DESTINATIONS` BEFORE the auto-imported extras so the dedup
 * logic in `enrich-destinations.ts` keeps the curated entry on a name
 * collision.
 */
import type { SeedDestination } from "../types";

export const CURATED_EXTRAS: SeedDestination[] = [
  // ───── Lake towns ──────────────────────────────────────────────
  {
    slug: "lake-george-ny",
    name: "Lake George",
    region: "Adirondacks",
    state: "NY",
    lat: 43.4276, lng: -73.7129,
    tags: ["scenic", "chill", "nature"],
    blurb: "Adirondack lake town with steamboat cruises, fall color, and a 32-mile shoreline of historic resorts.",
    attractions: [
      { name: "Lake George Steamboat", description: "Half-day cruises on a vintage steamboat past Million Dollar Beach." },
      { name: "Prospect Mountain", description: "5-mile drive to a 360° summit view across five states." },
      { name: "The Sagamore", description: "1883 Bolton Landing resort — tea on the porch, sunsets on the lake." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 0, CHI: 280, LAX: 420, SFO: 420, SEA: 420 }, lodgingPerNightUsd: 200, foodPerDayUsd: 65, activitiesPerDayUsd: 40 },
    bestSeasons: ["summer", "fall"],
    landscape: "lake",
    secondaryLandscapes: ["forest"],
    experiences: ["beaches", "scenic-drives", "hiking"],
    sceneryScore: 4,
    scenicSignals: ["fall-color", "water-feature"],
  },
  {
    slug: "mackinac-island-mi",
    name: "Mackinac Island",
    region: "Great Lakes",
    state: "MI",
    lat: 45.8492, lng: -84.6189,
    tags: ["scenic", "chill", "cultural"],
    blurb: "Car-free island in the strait between Lakes Huron and Michigan — horse-drawn carriages, Victorian porches, fudge shops.",
    attractions: [
      { name: "Grand Hotel", description: "1887 hotel with the world's longest porch and a strict afternoon dress code." },
      { name: "M-185 Loop", description: "8-mile bike loop around the island — only state highway with no cars." },
      { name: "Arch Rock", description: "50-ft limestone arch on the eastern shore." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 280, CHI: 220, LAX: 420, SFO: 440, SEA: 440 }, lodgingPerNightUsd: 280, foodPerDayUsd: 75, activitiesPerDayUsd: 50 },
    bestSeasons: ["summer", "fall"],
    landscape: "island",
    secondaryLandscapes: ["lake"],
    experiences: ["scenic-drives", "beaches", "museums"],
    sceneryScore: 4,
    scenicSignals: ["water-feature", "fall-color"],
  },
  {
    slug: "lake-placid-ny",
    name: "Lake Placid",
    region: "Adirondacks",
    state: "NY",
    lat: 44.2795, lng: -73.9799,
    tags: ["adventure", "scenic", "chill"],
    blurb: "Two-time Olympic village ringed by High Peaks — bobsled rides in summer, alpine skiing in winter.",
    attractions: [
      { name: "Whiteface Mountain", description: "Fifth-highest peak in NY — vehicle road to within 300 ft of the summit." },
      { name: "Olympic Center", description: "1980 Miracle on Ice rink — guided tours daily." },
      { name: "Mirror Lake", description: "Walkable lakefront downtown with kayak rentals." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 0, CHI: 300, LAX: 440, SFO: 440, SEA: 440 }, lodgingPerNightUsd: 220, foodPerDayUsd: 70, activitiesPerDayUsd: 60 },
    bestSeasons: ["summer", "fall", "winter"],
    landscape: "mountain",
    secondaryLandscapes: ["lake"],
    experiences: ["hiking", "scenic-drives", "wildlife"],
    sceneryScore: 5,
    scenicSignals: ["alpine", "fall-color", "water-feature"],
  },
  {
    slug: "door-county-wi",
    name: "Door County",
    region: "Great Lakes",
    state: "WI",
    lat: 45.0961, lng: -87.1316,
    tags: ["chill", "scenic", "foodie"],
    blurb: "75-mile peninsula between Green Bay and Lake Michigan — cherry orchards, fish boils, and 11 historic lighthouses.",
    attractions: [
      { name: "Cave Point County Park", description: "Limestone cliffs with sea-cave kayaking on Lake Michigan." },
      { name: "Peninsula State Park", description: "8-mile shoreline, Eagle Tower, and 20 miles of bike trails." },
      { name: "Wilson's Restaurant", description: "1906 Ephraim institution — fish boils on the patio." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 280, CHI: 0, LAX: 440, SFO: 440, SEA: 440 }, lodgingPerNightUsd: 180, foodPerDayUsd: 65, activitiesPerDayUsd: 35 },
    bestSeasons: ["summer", "fall"],
    landscape: "coast",
    secondaryLandscapes: ["lake", "forest"],
    experiences: ["beaches", "scenic-drives", "foodie"],
    sceneryScore: 4,
    scenicSignals: ["fall-color", "water-feature"],
  },
  {
    slug: "finger-lakes-ny",
    name: "Finger Lakes",
    region: "Finger Lakes",
    state: "NY",
    lat: 42.6526, lng: -76.7375,
    tags: ["foodie", "scenic", "chill"],
    blurb: "Eleven glacial lakes south of Rochester — Riesling country with farm-to-table inns and waterfall gorges.",
    attractions: [
      { name: "Watkins Glen State Park", description: "1.5-mile gorge trail past 19 waterfalls." },
      { name: "Seneca Lake Wine Trail", description: "35+ wineries on the longest finger lake — Riesling specialty." },
      { name: "Cornell Botanic Gardens", description: "Ithaca campus arboretum + native plant collections." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 0, CHI: 280, LAX: 420, SFO: 420, SEA: 440 }, lodgingPerNightUsd: 175, foodPerDayUsd: 80, activitiesPerDayUsd: 35 },
    bestSeasons: ["summer", "fall"],
    landscape: "lake",
    secondaryLandscapes: ["forest"],
    experiences: ["foodie", "scenic-drives", "hiking"],
    sceneryScore: 4,
    scenicSignals: ["fall-color", "water-feature"],
  },
  {
    slug: "flathead-lake-mt",
    name: "Flathead Lake",
    region: "Northern Rockies",
    state: "MT",
    lat: 47.8665, lng: -114.0935,
    tags: ["nature", "scenic", "chill"],
    blurb: "Largest natural freshwater lake west of the Mississippi, ringed by cherry orchards and the Mission Mountains.",
    attractions: [
      { name: "Wild Horse Island", description: "State park island with bighorn sheep and a 6-mile loop hike." },
      { name: "Polson Bay", description: "Sandy southern shore with kayak + paddleboard rentals." },
      { name: "Bigfork", description: "Lakeside village with summer playhouse and a working harbor." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 480, CHI: 380, LAX: 320, SFO: 320, SEA: 240 }, lodgingPerNightUsd: 220, foodPerDayUsd: 70, activitiesPerDayUsd: 40 },
    bestSeasons: ["summer", "fall"],
    landscape: "lake",
    secondaryLandscapes: ["mountain"],
    experiences: ["beaches", "hiking", "scenic-drives"],
    sceneryScore: 5,
    scenicSignals: ["alpine", "water-feature"],
  },

  // ───── Beach / coastal ─────────────────────────────────────────
  {
    slug: "sanibel-fl",
    name: "Sanibel Island",
    region: "Gulf Coast",
    state: "FL",
    lat: 26.4481, lng: -82.1131,
    tags: ["chill", "scenic", "nature"],
    blurb: "Shell-capital barrier island on Florida's Gulf Coast — sunset beaches, a wildlife refuge, and bike-friendly causeways.",
    attractions: [
      { name: "J.N. \"Ding\" Darling NWR", description: "6,400-acre mangrove refuge with a 4-mile wildlife drive." },
      { name: "Bowman's Beach", description: "Wide undeveloped beach famous for shell hunting at low tide." },
      { name: "Sanibel Lighthouse", description: "1884 lighthouse on the eastern tip with public fishing pier." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 220, CHI: 240, LAX: 340, SFO: 380, SEA: 380 }, lodgingPerNightUsd: 280, foodPerDayUsd: 80, activitiesPerDayUsd: 30 },
    bestSeasons: ["winter", "spring"],
    landscape: "island",
    secondaryLandscapes: ["coast"],
    experiences: ["beaches", "wildlife", "scenic-drives"],
    sceneryScore: 4,
    scenicSignals: ["water-feature", "wildlife"],
  },
  {
    slug: "st-augustine-fl",
    name: "St. Augustine",
    region: "Atlantic Coast",
    state: "FL",
    lat: 29.9012, lng: -81.3124,
    tags: ["cultural", "foodie", "chill"],
    blurb: "Oldest continuously occupied European settlement in the U.S. — 1565 Spanish fort, cobblestone alleys, beach 10 minutes east.",
    attractions: [
      { name: "Castillo de San Marcos", description: "1672 coquina-stone Spanish fort overlooking Matanzas Bay." },
      { name: "Lightner Museum", description: "Gilded-Age treasures inside Henry Flagler's 1888 Alcazar Hotel." },
      { name: "St. Augustine Beach", description: "Wide drivable beach a short hop east on A1A." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 240, CHI: 250, LAX: 360, SFO: 380, SEA: 400 }, lodgingPerNightUsd: 200, foodPerDayUsd: 70, activitiesPerDayUsd: 40 },
    bestSeasons: ["spring", "fall", "winter"],
    landscape: "coast",
    secondaryLandscapes: ["city"],
    experiences: ["museums", "foodie", "beaches"],
    sceneryScore: 3,
  },
  {
    slug: "newport-ri",
    name: "Newport",
    region: "New England",
    state: "RI",
    lat: 41.4901, lng: -71.3128,
    tags: ["cultural", "foodie", "scenic"],
    blurb: "Gilded-Age mansions, the 3.5-mile Cliff Walk, and one of the East Coast's tightest sailing harbors.",
    attractions: [
      { name: "The Breakers", description: "Vanderbilt's 70-room 1895 oceanfront cottage — guided audio tour." },
      { name: "Cliff Walk", description: "Public path between mansions and the Atlantic — 3.5 miles end to end." },
      { name: "Bowen's Wharf", description: "Working waterfront with raw bars and harbor cruises." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 0, CHI: 240, LAX: 420, SFO: 420, SEA: 440 }, lodgingPerNightUsd: 280, foodPerDayUsd: 90, activitiesPerDayUsd: 45 },
    bestSeasons: ["summer", "fall"],
    landscape: "coast",
    experiences: ["museums", "foodie", "beaches"],
    sceneryScore: 4,
    scenicSignals: ["coastal-cliffs"],
  },
  {
    slug: "cannon-beach-or",
    name: "Cannon Beach",
    region: "Pacific Northwest",
    state: "OR",
    lat: 45.8918, lng: -123.9615,
    tags: ["scenic", "chill", "foodie"],
    blurb: "Haystack Rock at low tide, a four-mile beach lined with weathered shingle cottages, and tide pools full of starfish.",
    attractions: [
      { name: "Haystack Rock", description: "235-ft sea stack — tide-pool walks at low tide, puffins in spring." },
      { name: "Ecola State Park", description: "Headland trails with views down to Tillamook Lighthouse." },
      { name: "Cannon Beach Bakery", description: "Sourdough loaves and marionberry pies daily since 1955." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 380, CHI: 320, LAX: 220, SFO: 200, SEA: 0 }, lodgingPerNightUsd: 260, foodPerDayUsd: 80, activitiesPerDayUsd: 25 },
    bestSeasons: ["summer", "fall"],
    landscape: "coast",
    experiences: ["beaches", "scenic-drives", "wildlife"],
    sceneryScore: 5,
    scenicSignals: ["iconic-vista", "coastal-cliffs", "wildlife"],
  },

  // ───── Islands ─────────────────────────────────────────────────
  {
    slug: "block-island-ri",
    name: "Block Island",
    region: "New England",
    state: "RI",
    lat: 41.1717, lng: -71.5586,
    tags: ["chill", "scenic", "nature"],
    blurb: "12 miles offshore from RI — pastoral cliffs, 17 miles of public beaches, no traffic lights.",
    attractions: [
      { name: "Mohegan Bluffs", description: "150-ft clay cliffs with stairs down to a wild Atlantic beach." },
      { name: "Crescent Beach", description: "Three-mile state beach on the eastern shore." },
      { name: "North Light", description: "1867 granite lighthouse at the island's wild northern tip." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 0, CHI: 260, LAX: 440, SFO: 440, SEA: 440 }, lodgingPerNightUsd: 320, foodPerDayUsd: 85, activitiesPerDayUsd: 30 },
    bestSeasons: ["summer"],
    landscape: "island",
    secondaryLandscapes: ["coast"],
    experiences: ["beaches", "scenic-drives", "hiking"],
    sceneryScore: 4,
    scenicSignals: ["coastal-cliffs", "iconic-vista"],
  },
  {
    slug: "san-juan-islands-wa",
    name: "San Juan Islands",
    region: "Pacific Northwest",
    state: "WA",
    lat: 48.5500, lng: -123.0000,
    tags: ["nature", "scenic", "chill"],
    blurb: "Archipelago in the Salish Sea — orca pods, pebble beaches, lavender farms, ferry-only access.",
    attractions: [
      { name: "Lime Kiln Point", description: "Whale-watching state park on San Juan Island's west side." },
      { name: "Roche Harbor", description: "Historic resort village with sailboat moorings and a sculpture park." },
      { name: "Mount Constitution", description: "Highest point in the islands — 360° view from a 1930s stone tower." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 420, CHI: 340, LAX: 240, SFO: 220, SEA: 0 }, lodgingPerNightUsd: 280, foodPerDayUsd: 80, activitiesPerDayUsd: 50 },
    bestSeasons: ["summer", "fall"],
    landscape: "island",
    secondaryLandscapes: ["coast", "forest"],
    experiences: ["wildlife", "scenic-drives", "hiking"],
    sceneryScore: 5,
    scenicSignals: ["iconic-vista", "wildlife", "coastal-cliffs"],
  },
  {
    slug: "catalina-ca",
    name: "Catalina Island",
    region: "Southern California",
    state: "CA",
    lat: 33.3879, lng: -118.4163,
    tags: ["chill", "scenic", "adventure"],
    blurb: "22 miles off LA — golf carts on cobblestone streets, snorkeling kelp forests, bison roaming the interior.",
    attractions: [
      { name: "Avalon Harbor", description: "Pastel waterfront village reached by ferry from Long Beach." },
      { name: "Catalina Casino", description: "1929 Art Deco circular hall — never gambling, always dancing." },
      { name: "Trans-Catalina Trail", description: "38-mile backbone trail across wild bison country." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 380, CHI: 260, LAX: 0, SFO: 180, SEA: 280 }, lodgingPerNightUsd: 260, foodPerDayUsd: 80, activitiesPerDayUsd: 45 },
    bestSeasons: ["spring", "summer", "fall"],
    landscape: "island",
    secondaryLandscapes: ["coast"],
    experiences: ["beaches", "hiking", "wildlife"],
    sceneryScore: 4,
    scenicSignals: ["water-feature", "wildlife"],
  },

  // ───── Scenic byways ──────────────────────────────────────────
  {
    slug: "highway-1-ca",
    name: "Pacific Coast Highway",
    region: "Central Coast",
    state: "CA",
    lat: 36.0, lng: -121.5,
    tags: ["scenic", "adventure"],
    blurb: "California State Route 1 from San Francisco to San Diego — 656 miles of cliffside driving past Big Sur, Hearst Castle, and Malibu.",
    attractions: [
      { name: "Bixby Bridge", description: "Iconic 1932 concrete arch span on the Big Sur stretch." },
      { name: "Hearst Castle", description: "Newspaper baron's 165-room hilltop estate at San Simeon." },
      { name: "Pfeiffer Beach", description: "Purple-sand cove south of Big Sur Village — sunset arch photo." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 380, CHI: 280, LAX: 0, SFO: 0, SEA: 240 }, lodgingPerNightUsd: 280, foodPerDayUsd: 85, activitiesPerDayUsd: 35 },
    bestSeasons: ["spring", "summer", "fall"],
    landscape: "coast",
    experiences: ["scenic-drives", "beaches", "hiking"],
    sceneryScore: 5,
    scenicSignals: ["iconic-vista", "coastal-cliffs", "redwood"],
  },
  {
    slug: "blue-ridge-parkway-nc",
    name: "Blue Ridge Parkway",
    region: "Appalachian Mountains",
    state: "NC",
    lat: 36.0, lng: -80.5,
    tags: ["scenic", "nature", "chill"],
    blurb: "America's longest linear park — 469 miles of mountain ridge from Shenandoah to Great Smoky Mountains, peak fall color in October.",
    attractions: [
      { name: "Linn Cove Viaduct", description: "Curved bridge wrapping Grandfather Mountain at MP 304." },
      { name: "Mabry Mill", description: "1903 working gristmill at MP 176 — pancakes and ground cornmeal." },
      { name: "Craggy Gardens", description: "Heath bald summit with rhododendron bloom mid-June." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 240, CHI: 240, LAX: 380, SFO: 400, SEA: 400 }, lodgingPerNightUsd: 160, foodPerDayUsd: 60, activitiesPerDayUsd: 25 },
    bestSeasons: ["spring", "summer", "fall"],
    landscape: "mountain",
    secondaryLandscapes: ["forest"],
    experiences: ["scenic-drives", "hiking", "wildlife"],
    sceneryScore: 5,
    scenicSignals: ["fall-color", "iconic-vista", "wildflower-bloom"],
  },
  {
    slug: "skyline-drive-va",
    name: "Skyline Drive",
    region: "Appalachian Mountains",
    state: "VA",
    lat: 38.5, lng: -78.4,
    tags: ["scenic", "nature"],
    blurb: "105-mile ridgeline through Shenandoah National Park — 75 overlooks, 500 miles of side trails, deer at every turnout.",
    attractions: [
      { name: "Old Rag Mountain", description: "9-mile ridge scramble — the toughest day hike in the park." },
      { name: "Dark Hollow Falls", description: "70-ft cascade reached by a 1.4-mile out-and-back from Big Meadows." },
      { name: "Big Meadows Lodge", description: "1939 stone lodge with rocking-chair porch and stargazing." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 0, CHI: 240, LAX: 380, SFO: 380, SEA: 400 }, lodgingPerNightUsd: 170, foodPerDayUsd: 55, activitiesPerDayUsd: 25 },
    bestSeasons: ["spring", "summer", "fall"],
    landscape: "mountain",
    secondaryLandscapes: ["forest"],
    experiences: ["scenic-drives", "hiking", "wildlife"],
    sceneryScore: 5,
    scenicSignals: ["fall-color", "iconic-vista", "wildlife"],
  },

  // ───── Missing major cities ────────────────────────────────────
  {
    slug: "pittsburgh-pa",
    name: "Pittsburgh",
    region: "Mid-Atlantic",
    state: "PA",
    lat: 40.4406, lng: -79.9959,
    tags: ["city", "cultural", "foodie"],
    blurb: "Steel-City turned tech-and-art hub at the meeting of three rivers — funicular inclines, Carnegie museums, pierogi everywhere.",
    attractions: [
      { name: "Duquesne Incline", description: "1877 funicular up Mt. Washington for the iconic three-rivers panorama." },
      { name: "Carnegie Museum of Natural History", description: "Dippy the Dinosaur and a top-five fossil collection." },
      { name: "Strip District", description: "Half-mile market street — Polish butchers, Italian bakeries, hot fish sandwiches." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 220, CHI: 220, LAX: 340, SFO: 380, SEA: 400 }, lodgingPerNightUsd: 170, foodPerDayUsd: 65, activitiesPerDayUsd: 25 },
    bestSeasons: ["spring", "summer", "fall"],
    landscape: "city",
    experiences: ["museums", "foodie"],
    sceneryScore: 3,
  },
  {
    slug: "memphis-tn",
    name: "Memphis",
    region: "Mid-South",
    state: "TN",
    lat: 35.1495, lng: -90.0490,
    tags: ["city", "cultural", "foodie"],
    blurb: "Birthplace of rock and the blues, home of dry-rub ribs — Beale Street nights, Sun Studio days.",
    attractions: [
      { name: "Graceland", description: "Elvis's 1957 Memphis estate — full mansion + Meditation Garden tour." },
      { name: "National Civil Rights Museum", description: "Built around the Lorraine Motel where MLK was assassinated." },
      { name: "Charlie Vergos' Rendezvous", description: "Basement-alley smokehouse for dry-rub ribs since 1948." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 240, CHI: 200, LAX: 320, SFO: 360, SEA: 400 }, lodgingPerNightUsd: 160, foodPerDayUsd: 65, activitiesPerDayUsd: 30 },
    bestSeasons: ["spring", "fall"],
    landscape: "city",
    experiences: ["museums", "foodie"],
    sceneryScore: 2,
  },
  {
    slug: "minneapolis-mn",
    name: "Minneapolis",
    region: "Upper Midwest",
    state: "MN",
    lat: 44.9778, lng: -93.2650,
    tags: ["city", "cultural", "foodie"],
    blurb: "City of lakes and chain-of-skyway winters — Walker Art Center, Prince's Paisley Park, the Mississippi headwaters.",
    attractions: [
      { name: "Walker Art Center", description: "Contemporary museum with the iconic Spoonbridge and Cherry sculpture." },
      { name: "Chain of Lakes", description: "Calhoun, Harriet, and Cedar — 13 miles of paved paths around three lakes." },
      { name: "Mill City Museum", description: "Built into the ruins of the Washburn A Mill on the Mississippi." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 280, CHI: 220, LAX: 380, SFO: 420, SEA: 420 }, lodgingPerNightUsd: 180, foodPerDayUsd: 70, activitiesPerDayUsd: 30 },
    bestSeasons: ["summer", "fall"],
    landscape: "city",
    secondaryLandscapes: ["lake"],
    experiences: ["museums", "foodie"],
    sceneryScore: 3,
  },
  {
    slug: "louisville-ky",
    name: "Louisville",
    region: "Mid-South",
    state: "KY",
    lat: 38.2527, lng: -85.7585,
    tags: ["city", "foodie", "cultural"],
    blurb: "Bourbon, the Kentucky Derby, and a downtown dotted with distilleries and the world's largest baseball bat.",
    attractions: [
      { name: "Churchill Downs", description: "Twin-spired track that's hosted the Derby since 1875." },
      { name: "Louisville Slugger Museum", description: "Behind-the-scenes bat factory tour with a 120-ft bat out front." },
      { name: "Urban Bourbon Trail", description: "47-stop downtown distillery + bourbon-bar walk." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 240, CHI: 220, LAX: 360, SFO: 400, SEA: 420 }, lodgingPerNightUsd: 160, foodPerDayUsd: 65, activitiesPerDayUsd: 30 },
    bestSeasons: ["spring", "fall"],
    landscape: "city",
    experiences: ["museums", "foodie"],
    sceneryScore: 2,
  },
  {
    slug: "milwaukee-wi",
    name: "Milwaukee",
    region: "Great Lakes",
    state: "WI",
    lat: 43.0389, lng: -87.9065,
    tags: ["city", "foodie", "cultural"],
    blurb: "Lake Michigan beer city — Calatrava-winged art museum, frozen custard stands, and the Harley-Davidson archive.",
    attractions: [
      { name: "Milwaukee Art Museum", description: "Calatrava's 2001 white-winged Quadracci Pavilion on the lakefront." },
      { name: "Harley-Davidson Museum", description: "20-acre campus with 450+ motorcycles dating to 1903." },
      { name: "Lakefront Brewery", description: "Riverside brewery tour ending with a Friday-night fish fry." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 260, CHI: 0, LAX: 380, SFO: 400, SEA: 420 }, lodgingPerNightUsd: 170, foodPerDayUsd: 65, activitiesPerDayUsd: 30 },
    bestSeasons: ["summer", "fall"],
    landscape: "city",
    secondaryLandscapes: ["lake"],
    experiences: ["museums", "foodie"],
    sceneryScore: 3,
  },

  // ───── Mountain towns ─────────────────────────────────────────
  {
    slug: "park-city-ut",
    name: "Park City",
    region: "Wasatch Range",
    state: "UT",
    lat: 40.6461, lng: -111.4980,
    tags: ["adventure", "scenic", "foodie"],
    blurb: "Silver-mining town turned skier's mecca — 7,300 acres of lifts, Sundance Film Festival in January, mountain biking in summer.",
    attractions: [
      { name: "Park City Mountain", description: "Largest ski resort in the U.S. — 7,300 acres of lift-served terrain." },
      { name: "Historic Main Street", description: "Restored 1880s mining strip with bourbon bars and gallery row." },
      { name: "Olympic Park", description: "2002 Olympic site — bobsled rides and Nordic ski-jump training." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 360, CHI: 280, LAX: 240, SFO: 240, SEA: 280 }, lodgingPerNightUsd: 320, foodPerDayUsd: 85, activitiesPerDayUsd: 90 },
    bestSeasons: ["summer", "winter"],
    landscape: "mountain",
    experiences: ["hiking", "scenic-drives", "foodie"],
    sceneryScore: 4,
    scenicSignals: ["alpine"],
  },
  {
    slug: "telluride-co",
    name: "Telluride",
    region: "San Juan Mountains",
    state: "CO",
    lat: 37.9375, lng: -107.8123,
    tags: ["scenic", "adventure", "chill"],
    blurb: "Box-canyon Victorian mining town accessed by a free gondola — bluegrass festival, 360° peaks, no chains in sight.",
    attractions: [
      { name: "Bridal Veil Falls", description: "Tallest free-falling waterfall in Colorado — 365-ft drop at the canyon's head." },
      { name: "Telluride Ski Resort", description: "2,000 vertical feet on three peaks via the gondola from town." },
      { name: "Bridge Street", description: "Three-block historic strip with the New Sheridan Hotel and Floradora Saloon." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 460, CHI: 360, LAX: 320, SFO: 320, SEA: 360 }, lodgingPerNightUsd: 380, foodPerDayUsd: 95, activitiesPerDayUsd: 80 },
    bestSeasons: ["summer", "fall", "winter"],
    landscape: "mountain",
    secondaryLandscapes: ["canyon"],
    experiences: ["hiking", "scenic-drives", "foodie"],
    sceneryScore: 5,
    scenicSignals: ["alpine", "iconic-vista", "fall-color"],
  },
  {
    slug: "stowe-vt",
    name: "Stowe",
    region: "New England",
    state: "VT",
    lat: 44.4654, lng: -72.6874,
    tags: ["scenic", "chill", "foodie"],
    blurb: "Storybook Vermont village under Mt. Mansfield — covered bridges, syrup farms, and the Trapp Family Lodge of Sound of Music fame.",
    attractions: [
      { name: "Stowe Mountain Resort", description: "Vermont's largest ski area on Mt. Mansfield — gondola rides year-round." },
      { name: "Trapp Family Lodge", description: "Austrian-style mountain inn with brewery and 60+ km of cross-country trails." },
      { name: "Smugglers' Notch", description: "VT-108 mountain pass between Stowe and Cambridge — closes in winter." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 220, CHI: 280, LAX: 440, SFO: 440, SEA: 440 }, lodgingPerNightUsd: 260, foodPerDayUsd: 80, activitiesPerDayUsd: 65 },
    bestSeasons: ["summer", "fall", "winter"],
    landscape: "mountain",
    secondaryLandscapes: ["forest"],
    experiences: ["hiking", "scenic-drives", "foodie"],
    sceneryScore: 5,
    scenicSignals: ["fall-color", "alpine"],
  },

  // ───── Wine country / wellness ────────────────────────────────
  {
    slug: "napa-valley-ca",
    name: "Napa Valley",
    region: "Wine Country",
    state: "CA",
    lat: 38.5025, lng: -122.2654,
    tags: ["foodie", "scenic", "chill"],
    blurb: "30 miles of cabernet vineyards along Highway 29 — Michelin-star kitchens, hot-air balloons at dawn, mud baths in Calistoga.",
    attractions: [
      { name: "Inglenook", description: "Coppola-restored 1879 estate — Bordeaux-blend Rubicon and a film museum." },
      { name: "Oxbow Public Market", description: "Riverside market hall with oysters, Hog Island clams, and Model Bakery muffins." },
      { name: "Domaine Carneros", description: "Sparkling-wine château by Taittinger — terrace tastings overlooking the Carneros hills." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 380, CHI: 280, LAX: 180, SFO: 0, SEA: 280 }, lodgingPerNightUsd: 380, foodPerDayUsd: 120, activitiesPerDayUsd: 80 },
    bestSeasons: ["spring", "summer", "fall"],
    landscape: "city",
    secondaryLandscapes: ["forest"],
    experiences: ["foodie", "scenic-drives"],
    sceneryScore: 4,
    scenicSignals: ["fall-color"],
  },
  {
    slug: "calistoga-ca",
    name: "Calistoga",
    region: "Wine Country",
    state: "CA",
    lat: 38.5788, lng: -122.5797,
    tags: ["chill", "foodie", "scenic"],
    blurb: "Northern-Napa spa town built on volcanic mud baths and old-faithful geyser — quieter and cheaper than St. Helena.",
    attractions: [
      { name: "Calistoga Mud Baths", description: "Half a dozen 1900s-era spas with mineral-water pools and volcanic-ash mud." },
      { name: "Old Faithful Geyser of California", description: "Erupts every 30 minutes — small park with its own llamas." },
      { name: "Sterling Vineyards", description: "Hilltop winery reached by aerial gondola — sweeping valley view." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 380, CHI: 280, LAX: 200, SFO: 0, SEA: 280 }, lodgingPerNightUsd: 280, foodPerDayUsd: 90, activitiesPerDayUsd: 80 },
    bestSeasons: ["spring", "fall"],
    landscape: "city",
    secondaryLandscapes: ["mountain"],
    experiences: ["hot-springs", "foodie", "scenic-drives"],
    sceneryScore: 4,
  },
  {
    slug: "hot-springs-ar",
    name: "Hot Springs",
    region: "Ouachita Mountains",
    state: "AR",
    lat: 34.5037, lng: -93.0552,
    tags: ["chill", "cultural", "nature"],
    blurb: "Bathhouse Row in the only national park inside a city — 47 thermal springs and 1920s spa facades fully restored.",
    attractions: [
      { name: "Bathhouse Row", description: "Eight 1900s spa buildings — Buckstaff and Quapaw still soaking guests." },
      { name: "Hot Springs National Park", description: "5,000-acre forest above the springs with 26 miles of trails." },
      { name: "Mountain Tower", description: "216-ft observation tower at the top of Hot Springs Mountain." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 320, CHI: 240, LAX: 360, SFO: 400, SEA: 420 }, lodgingPerNightUsd: 160, foodPerDayUsd: 55, activitiesPerDayUsd: 45 },
    bestSeasons: ["spring", "fall"],
    landscape: "mountain",
    secondaryLandscapes: ["forest"],
    experiences: ["hot-springs", "hiking", "museums"],
    sceneryScore: 3,
  },

  // ───── Quirky gaps ────────────────────────────────────────────
  {
    slug: "moab-ut",
    name: "Moab",
    region: "Colorado Plateau",
    state: "UT",
    lat: 38.5733, lng: -109.5498,
    tags: ["adventure", "scenic", "nature"],
    blurb: "Red-rock adventure base between Arches and Canyonlands — mountain biking on Slickrock, rafting the Colorado, mesa stargazing.",
    attractions: [
      { name: "Slickrock Bike Trail", description: "10.6-mile loop on bare sandstone — birthplace of mountain biking." },
      { name: "Dead Horse Point State Park", description: "2,000-ft canyon overlook 30 minutes from town." },
      { name: "Colorado Riverway", description: "Class II–III rafting on the Colorado below Moab." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 440, CHI: 340, LAX: 280, SFO: 280, SEA: 320 }, lodgingPerNightUsd: 200, foodPerDayUsd: 70, activitiesPerDayUsd: 75 },
    bestSeasons: ["spring", "fall"],
    landscape: "desert",
    secondaryLandscapes: ["canyon"],
    experiences: ["hiking", "scenic-drives", "wildlife"],
    sceneryScore: 5,
    scenicSignals: ["iconic-vista", "geological-feature", "dark-sky"],
  },
  {
    slug: "bar-harbor-me",
    name: "Bar Harbor",
    region: "Coastal Maine",
    state: "ME",
    lat: 44.3876, lng: -68.2039,
    tags: ["scenic", "foodie", "chill"],
    blurb: "Mount Desert Island gateway to Acadia — lobster shacks, sailboat harbor, sunrise on Cadillac Mountain.",
    attractions: [
      { name: "Cadillac Mountain", description: "First U.S. sunrise from October to March — drive to the summit." },
      { name: "Park Loop Road", description: "27-mile scenic drive past Sand Beach, Thunder Hole, Otter Cliffs." },
      { name: "Stewman's Lobster Pound", description: "Pier-side picnic-bench lobster shack on Bar Harbor's harbor." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 240, CHI: 320, LAX: 450, SFO: 450, SEA: 460 }, lodgingPerNightUsd: 240, foodPerDayUsd: 85, activitiesPerDayUsd: 35 },
    bestSeasons: ["summer", "fall"],
    landscape: "coast",
    secondaryLandscapes: ["island", "forest"],
    experiences: ["scenic-drives", "foodie", "hiking"],
    sceneryScore: 5,
    scenicSignals: ["coastal-cliffs", "fall-color", "iconic-vista"],
  },
  {
    slug: "florida-keys-fl",
    name: "Florida Keys",
    region: "Gulf Coast",
    state: "FL",
    lat: 24.7, lng: -81.4,
    tags: ["scenic", "chill", "foodie"],
    blurb: "113-mile US-1 island chain from Miami to Key West — turquoise water, conch fritters, sunset at Mallory Square.",
    attractions: [
      { name: "Seven Mile Bridge", description: "Iconic span between Knight's Key and Little Duck Key." },
      { name: "Bahia Honda State Park", description: "Voted top US beach — old railroad bridge view from sand level." },
      { name: "John Pennekamp Coral Reef SP", description: "First underwater park in the US — glass-bottom boats and snorkel reef." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 260, CHI: 280, LAX: 380, SFO: 420, SEA: 440 }, lodgingPerNightUsd: 280, foodPerDayUsd: 80, activitiesPerDayUsd: 50 },
    bestSeasons: ["winter", "spring"],
    landscape: "island",
    secondaryLandscapes: ["coast"],
    experiences: ["beaches", "scenic-drives", "wildlife"],
    sceneryScore: 5,
    scenicSignals: ["iconic-vista", "water-feature", "coastal-cliffs"],
  },
];
