import type { SeedDestination } from "../types";

/**
 * Hand-curated US destinations reachable from NYC / CHI / LAX / SFO / SEA.
 * Single source of truth — `scripts/generate-seed-sql.ts` derives the SQL.
 *
 * Photo URLs are populated by `scripts/prefetch-place-photos.ts`, which
 * requires GOOGLE_PLACES_API_KEY. Until that runs, hero_photo_url is empty
 * and the UI falls back to a deterministic Unsplash query stub.
 *
 * Cost bands are rough planning estimates, not quotes. Amadeus may override
 * them at runtime when its test env returns usable data.
 */
export const DESTINATIONS: SeedDestination[] = [
  // ───── Cities ─────────────────────────────────────────────────
  {
    slug: "boston-ma",
    name: "Boston",
    region: "New England",
    state: "MA",
    lat: 42.3601, lng: -71.0589,
    tags: ["city", "cultural", "foodie"],
    blurb: "Walkable colonial city with serious chowder, world-class museums, and a coastline minutes from downtown.",
    attractions: [
      { name: "Freedom Trail", description: "2.5-mile self-guided history walk through 16 sites." },
      { name: "Museum of Fine Arts", description: "One of the most comprehensive art collections in the Americas." },
      { name: "North End", description: "Italian neighborhood with the city's best red-sauce." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 180, CHI: 240, LAX: 380, SFO: 380, SEA: 380 }, lodgingPerNightUsd: 220, foodPerDayUsd: 80, activitiesPerDayUsd: 30 },
    bestSeasons: ["spring", "summer", "fall"],
  },
  {
    slug: "charleston-sc",
    name: "Charleston",
    region: "Lowcountry",
    state: "SC",
    lat: 32.7765, lng: -79.9311,
    tags: ["city", "foodie", "cultural", "scenic"],
    blurb: "Pastel Antebellum streets, oyster bars, and a food scene that punches three weight classes above its size.",
    attractions: [
      { name: "Rainbow Row", description: "13 restored Georgian houses on East Bay." },
      { name: "Husk", description: "Lowcountry tasting menu in a Queen Anne mansion." },
      { name: "Sullivan's Island", description: "10-minute drive to wide, uncrowded beaches." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 230, CHI: 260, LAX: 380, SFO: 410, SEA: 430 }, lodgingPerNightUsd: 240, foodPerDayUsd: 90, activitiesPerDayUsd: 35 },
    bestSeasons: ["spring", "fall"],
  },
  {
    slug: "savannah-ga",
    name: "Savannah",
    region: "Lowcountry",
    state: "GA",
    lat: 32.0809, lng: -81.0912,
    tags: ["city", "scenic", "chill", "cultural"],
    blurb: "22 squares of moss-draped oak under a slow Southern pace — a city that feels half garden.",
    attractions: [
      { name: "Forsyth Park", description: "30 acres of fountains and live oaks at the historic district's south end." },
      { name: "Bonaventure Cemetery", description: "Riverside burial ground famous for Spanish moss and statuary." },
      { name: "Tybee Island", description: "20 minutes east, walkable beach town with a pier and lighthouse." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 220, CHI: 260, LAX: 400, SFO: 420, SEA: 440 }, lodgingPerNightUsd: 200, foodPerDayUsd: 75, activitiesPerDayUsd: 25 },
    bestSeasons: ["spring", "fall"],
  },
  {
    slug: "new-orleans-la",
    name: "New Orleans",
    region: "Gulf Coast",
    state: "LA",
    lat: 29.9511, lng: -90.0715,
    tags: ["city", "foodie", "nightlife", "cultural"],
    blurb: "Creole, jazz, beignets, and balcony shadows — the most distinctive food city in America.",
    attractions: [
      { name: "French Quarter", description: "Iron-laced balconies, Bourbon and Royal Streets, Café du Monde." },
      { name: "Frenchmen Street", description: "Live music every night without the Bourbon-Street frenzy." },
      { name: "Garden District", description: "Walking tour through Greek Revival mansions and Lafayette Cemetery No. 1." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 220, CHI: 200, LAX: 280, SFO: 320, SEA: 380 }, lodgingPerNightUsd: 200, foodPerDayUsd: 95, activitiesPerDayUsd: 30 },
    bestSeasons: ["spring", "fall", "winter"],
  },
  {
    slug: "nashville-tn",
    name: "Nashville",
    region: "Mid-South",
    state: "TN",
    lat: 36.1627, lng: -86.7816,
    tags: ["city", "nightlife", "foodie", "cultural"],
    blurb: "Honky-tonks and hot chicken, plus a younger food scene quietly rivaling the music.",
    attractions: [
      { name: "Country Music Hall of Fame", description: "Definitive collection of country music history." },
      { name: "Hattie B's", description: "The hot chicken benchmark — go to Charlotte Ave. before noon." },
      { name: "Ryman Auditorium", description: "Original Grand Ole Opry, still hosting shows." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 220, CHI: 180, LAX: 320, SFO: 360, SEA: 380 }, lodgingPerNightUsd: 230, foodPerDayUsd: 80, activitiesPerDayUsd: 35 },
    bestSeasons: ["spring", "fall"],
  },
  {
    slug: "austin-tx",
    name: "Austin",
    region: "Texas Hill Country",
    state: "TX",
    lat: 30.2672, lng: -97.7431,
    tags: ["city", "foodie", "nightlife", "scenic"],
    blurb: "Hill-country lakes, taco trailers, and live music seven nights a week.",
    attractions: [
      { name: "Franklin Barbecue", description: "Worth the line — at minimum once in your life." },
      { name: "Barton Springs", description: "70°F spring-fed pool in Zilker Park, year-round." },
      { name: "South Congress", description: "Vintage shops, food trailers, the boot store from every Austin photo." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 260, CHI: 220, LAX: 240, SFO: 280, SEA: 320 }, lodgingPerNightUsd: 240, foodPerDayUsd: 75, activitiesPerDayUsd: 30 },
    bestSeasons: ["spring", "fall"],
  },
  {
    slug: "asheville-nc",
    name: "Asheville",
    region: "Blue Ridge",
    state: "NC",
    lat: 35.5951, lng: -82.5515,
    tags: ["city", "scenic", "foodie", "nature"],
    blurb: "Mountain town with America's biggest house, a craft-brewery per capita rivaling Portland, and the Blue Ridge Parkway out the back door.",
    attractions: [
      { name: "Biltmore Estate", description: "America's largest privately owned home; gardens are the move in spring." },
      { name: "Blue Ridge Parkway", description: "Scenic drive immediately out of town — stop at Craggy Gardens." },
      { name: "River Arts District", description: "Working-artist warehouses along the French Broad." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 250, CHI: 240, LAX: 380, SFO: 410, SEA: 420 }, lodgingPerNightUsd: 220, foodPerDayUsd: 75, activitiesPerDayUsd: 35 },
    bestSeasons: ["spring", "fall"],
  },
  {
    slug: "santa-fe-nm",
    name: "Santa Fe",
    region: "Southwest",
    state: "NM",
    lat: 35.6870, lng: -105.9378,
    tags: ["cultural", "scenic", "foodie", "chill"],
    blurb: "Adobe-walled art capital at 7,000 ft — green chile, Georgia O'Keeffe country, sunsets that feel staged.",
    attractions: [
      { name: "Canyon Road", description: "Half-mile of galleries and sculpture gardens." },
      { name: "Meow Wolf", description: "Immersive art installation — book ahead." },
      { name: "Tent Rocks", description: "45-minute drive; slot canyons and hoodoos in Kasha-Katuwe." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 380, CHI: 320, LAX: 240, SFO: 260, SEA: 320 }, lodgingPerNightUsd: 230, foodPerDayUsd: 75, activitiesPerDayUsd: 35 },
    bestSeasons: ["spring", "summer", "fall"],
  },

  // ───── Nature / National Parks ────────────────────────────────
  {
    slug: "acadia-np",
    name: "Acadia National Park",
    region: "Coastal Maine",
    state: "ME",
    lat: 44.3386, lng: -68.2733,
    tags: ["nature", "scenic", "adventure"],
    blurb: "Pink-granite headlands meeting the Atlantic — the only fjord on the eastern seaboard, with a side of lobster rolls.",
    attractions: [
      { name: "Cadillac Mountain", description: "Highest point on the US Atlantic — first US sunrise Oct–Mar." },
      { name: "Jordan Pond Path", description: "3.3-mile loop with popovers at the end." },
      { name: "Bar Harbor", description: "Walkable base town for the park; ferries to Schoodic Peninsula." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 240, CHI: 320, LAX: 480, SFO: 480, SEA: 460 }, lodgingPerNightUsd: 240, foodPerDayUsd: 75, activitiesPerDayUsd: 25 },
    bestSeasons: ["summer", "fall"],
  },
  {
    slug: "yellowstone-np",
    name: "Yellowstone National Park",
    region: "Greater Yellowstone",
    state: "WY",
    lat: 44.4280, lng: -110.5885,
    tags: ["nature", "adventure", "scenic"],
    blurb: "Geysers, super-volcano calderas, and bison the size of cars — America's first national park, still its loudest.",
    attractions: [
      { name: "Old Faithful + Upper Geyser Basin", description: "Highest concentration of geysers on Earth." },
      { name: "Lamar Valley", description: "America's Serengeti — wolves, bison, bears at dawn." },
      { name: "Grand Prismatic Spring", description: "Largest hot spring in the US — overlook trail for the iconic shot." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 380, CHI: 340, LAX: 340, SFO: 340, SEA: 280 }, lodgingPerNightUsd: 280, foodPerDayUsd: 70, activitiesPerDayUsd: 30 },
    bestSeasons: ["summer", "fall"],
  },
  {
    slug: "yosemite-np",
    name: "Yosemite National Park",
    region: "Sierra Nevada",
    state: "CA",
    lat: 37.8651, lng: -119.5383,
    tags: ["nature", "adventure", "scenic"],
    blurb: "Granite cathedrals, 2,400-ft waterfalls, and giant sequoias — the most iconic vertical landscape in America.",
    attractions: [
      { name: "Tunnel View", description: "First arrival shot — El Cap, Half Dome, Bridalveil all in one frame." },
      { name: "Glacier Point", description: "Drive-up overlook; sunset on Half Dome's north face." },
      { name: "Mist Trail", description: "Climbs alongside Vernal and Nevada Falls — wet in spring." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 320, CHI: 280, LAX: 200, SFO: 160, SEA: 240 }, lodgingPerNightUsd: 260, foodPerDayUsd: 65, activitiesPerDayUsd: 25 },
    bestSeasons: ["spring", "summer", "fall"],
  },
  {
    slug: "zion-np",
    name: "Zion National Park",
    region: "Colorado Plateau",
    state: "UT",
    lat: 37.2982, lng: -113.0263,
    tags: ["nature", "adventure", "scenic"],
    blurb: "Vermillion canyon walls and the Virgin River cutting through them — slot canyons and Angels Landing.",
    attractions: [
      { name: "Angels Landing", description: "5-mile out-and-back; chained-cliff section is unforgettable. Permit required." },
      { name: "The Narrows", description: "Wading the Virgin River through a slot canyon — rent neoprene in spring." },
      { name: "Springdale", description: "Walkable gateway town with the shuttle terminus." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 320, CHI: 260, LAX: 180, SFO: 220, SEA: 260 }, lodgingPerNightUsd: 250, foodPerDayUsd: 65, activitiesPerDayUsd: 30 },
    bestSeasons: ["spring", "fall"],
  },
  {
    slug: "joshua-tree-np",
    name: "Joshua Tree National Park",
    region: "Mojave/Colorado Deserts",
    state: "CA",
    lat: 33.8734, lng: -115.9010,
    tags: ["nature", "scenic", "chill", "adventure"],
    blurb: "Two deserts meeting — Seussian Joshua trees, granite jumbles, dark-sky stargazing 2 hr from LA.",
    attractions: [
      { name: "Hidden Valley loop", description: "1-mile flat trail through monzogranite — great for first afternoon." },
      { name: "Keys View", description: "Drive-up overlook of the Coachella Valley and San Andreas Fault." },
      { name: "Pioneertown", description: "Old Western movie set turned cocktail town outside the park." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 320, CHI: 260, LAX: 80, SFO: 180, SEA: 260 }, lodgingPerNightUsd: 200, foodPerDayUsd: 60, activitiesPerDayUsd: 20 },
    bestSeasons: ["spring", "fall", "winter"],
  },
  {
    slug: "smoky-mountains-np",
    name: "Great Smoky Mountains",
    region: "Southern Appalachians",
    state: "TN",
    lat: 35.6118, lng: -83.4895,
    tags: ["nature", "scenic", "chill"],
    blurb: "Most-visited US national park — old-growth forest, Cherokee history, and a haze that's actually plant exhalation.",
    attractions: [
      { name: "Cades Cove loop", description: "11-mile drive through historic homesteads with bear sightings most mornings." },
      { name: "Clingmans Dome", description: "Highest point in the park; observation tower at 6,643 ft." },
      { name: "Gatlinburg", description: "Walkable gateway town for moonshine, ski lifts, and trails." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 240, CHI: 220, LAX: 360, SFO: 380, SEA: 400 }, lodgingPerNightUsd: 180, foodPerDayUsd: 60, activitiesPerDayUsd: 20 },
    bestSeasons: ["spring", "summer", "fall"],
  },
  {
    slug: "glacier-np",
    name: "Glacier National Park",
    region: "Northern Rockies",
    state: "MT",
    lat: 48.7596, lng: -113.7870,
    tags: ["nature", "adventure", "scenic"],
    blurb: "Crown of the Continent — turquoise lakes, hanging valleys, and Going-to-the-Sun Road carving the divide.",
    attractions: [
      { name: "Going-to-the-Sun Road", description: "50-mile alpine drive over Logan Pass — open mid-June to early Oct." },
      { name: "Highline Trail", description: "11.8-mile ridgewalk with mountain-goat traffic." },
      { name: "Lake McDonald", description: "Multicolored pebbles, big lake, west-side base for lodging." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 360, CHI: 320, LAX: 320, SFO: 320, SEA: 220 }, lodgingPerNightUsd: 280, foodPerDayUsd: 70, activitiesPerDayUsd: 30 },
    bestSeasons: ["summer"],
  },
  {
    slug: "olympic-np",
    name: "Olympic National Park",
    region: "Pacific Northwest",
    state: "WA",
    lat: 47.8021, lng: -123.6044,
    tags: ["nature", "scenic", "adventure"],
    blurb: "Three ecosystems in one park — temperate rainforest, alpine ridge, and Pacific coastline with sea stacks.",
    attractions: [
      { name: "Hoh Rainforest", description: "Hall of Mosses — densest temperate rainforest in the world." },
      { name: "Hurricane Ridge", description: "Drive-up subalpine views from Port Angeles." },
      { name: "Rialto Beach", description: "Hike to Hole-in-the-Wall at low tide for sea-stack tide pools." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 380, CHI: 320, LAX: 220, SFO: 220, SEA: 60 }, lodgingPerNightUsd: 220, foodPerDayUsd: 65, activitiesPerDayUsd: 25 },
    bestSeasons: ["summer", "fall"],
  },

  // ───── Mountain / Small towns ─────────────────────────────────
  {
    slug: "aspen-co",
    name: "Aspen",
    region: "Rockies",
    state: "CO",
    lat: 39.1911, lng: -106.8175,
    tags: ["scenic", "adventure", "foodie", "chill"],
    blurb: "Four mountains, the Maroon Bells, and a downtown that's somehow both a ski town and a Michelin destination.",
    attractions: [
      { name: "Maroon Bells", description: "Most-photographed peaks in North America — shuttle-only mid-summer." },
      { name: "Aspen Mountain", description: "Gondola from downtown to 11,212 ft — lift-served hiking in summer." },
      { name: "Wheeler Opera House", description: "1889 venue — small concerts in a perfect 500-seat hall." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 420, CHI: 360, LAX: 280, SFO: 320, SEA: 360 }, lodgingPerNightUsd: 380, foodPerDayUsd: 110, activitiesPerDayUsd: 40 },
    bestSeasons: ["summer", "fall", "winter"],
  },
  {
    slug: "jackson-hole-wy",
    name: "Jackson Hole",
    region: "Greater Yellowstone",
    state: "WY",
    lat: 43.4799, lng: -110.7624,
    tags: ["scenic", "adventure", "nature", "foodie"],
    blurb: "Teton Range out the front door, elk antler arches downtown, and the gateway to two national parks.",
    attractions: [
      { name: "Grand Teton National Park", description: "Schwabacher Landing at sunrise; Inspiration Point hike at Jenny Lake." },
      { name: "National Elk Refuge", description: "Sleigh rides through the world's largest elk herd Dec–Mar." },
      { name: "Snake River float", description: "Half-day raft trip with the Tetons as a backdrop." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 420, CHI: 380, LAX: 320, SFO: 340, SEA: 320 }, lodgingPerNightUsd: 320, foodPerDayUsd: 95, activitiesPerDayUsd: 50 },
    bestSeasons: ["summer", "fall", "winter"],
  },
  {
    slug: "sedona-az",
    name: "Sedona",
    region: "Colorado Plateau",
    state: "AZ",
    lat: 34.8697, lng: -111.7610,
    tags: ["scenic", "adventure", "chill", "nature"],
    blurb: "Red-rock buttes 2 hr north of Phoenix — vortexes, slickrock hikes, and one of the prettiest drives in America.",
    attractions: [
      { name: "Cathedral Rock", description: "1.2-mile out-and-back; classic Sedona postcard view." },
      { name: "Oak Creek Canyon", description: "Drive AZ-89A north toward Flagstaff — switchbacks through red rock." },
      { name: "Tlaquepaque Arts Village", description: "Adobe-walled gallery district along Oak Creek." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 320, CHI: 260, LAX: 180, SFO: 220, SEA: 280 }, lodgingPerNightUsd: 280, foodPerDayUsd: 75, activitiesPerDayUsd: 30 },
    bestSeasons: ["spring", "fall"],
  },
  {
    slug: "big-sur-ca",
    name: "Big Sur",
    region: "Central Coast",
    state: "CA",
    lat: 36.2704, lng: -121.8081,
    tags: ["scenic", "chill", "nature"],
    blurb: "90 miles of cliff-and-redwood coastline along Highway 1 — the prettiest road trip on the West Coast.",
    attractions: [
      { name: "McWay Falls", description: "80-ft waterfall onto a beach in Julia Pfeiffer Burns SP." },
      { name: "Bixby Bridge", description: "Iconic 1932 span — pull off northbound for the photo." },
      { name: "Nepenthe", description: "Cliffside restaurant with a 40-mile coastline view." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 320, CHI: 280, LAX: 160, SFO: 100, SEA: 220 }, lodgingPerNightUsd: 360, foodPerDayUsd: 95, activitiesPerDayUsd: 30 },
    bestSeasons: ["spring", "summer", "fall"],
  },

  // ───── Mixed: islands / regions / coastal ─────────────────────
  {
    slug: "maui-hi",
    name: "Maui",
    region: "Hawaiian Islands",
    state: "HI",
    lat: 20.7984, lng: -156.3319,
    tags: ["scenic", "nature", "chill", "adventure"],
    blurb: "Volcanic crater above the clouds, a 600-curve road through jungle, and beach towns on the leeward side.",
    attractions: [
      { name: "Haleakalā Sunrise", description: "Drive to 10,023 ft for sunrise above the clouds — reservation required." },
      { name: "Road to Hana", description: "All-day cliff drive with waterfalls, pools, and black-sand beach." },
      { name: "Molokini Crater", description: "Snorkel a half-submerged volcanic crater off the south shore." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 580, CHI: 480, LAX: 320, SFO: 320, SEA: 320 }, lodgingPerNightUsd: 380, foodPerDayUsd: 95, activitiesPerDayUsd: 80 },
    bestSeasons: ["spring", "summer", "fall", "winter"],
  },
  {
    slug: "kauai-hi",
    name: "Kauai",
    region: "Hawaiian Islands",
    state: "HI",
    lat: 22.0964, lng: -159.5261,
    tags: ["scenic", "nature", "adventure", "chill"],
    blurb: "The 'Garden Isle' — Nā Pali sea cliffs, a Grand-Canyon-of-the-Pacific, and 80% of the island unreachable by road.",
    attractions: [
      { name: "Nā Pali Coast", description: "Boat or helicopter tour — 17 miles of sea cliffs you cannot drive to." },
      { name: "Waimea Canyon", description: "Mark Twain's 'Grand Canyon of the Pacific' — drive to the rim lookouts." },
      { name: "Hanalei Bay", description: "Crescent bay with mountain backdrop on the north shore." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 600, CHI: 500, LAX: 340, SFO: 340, SEA: 360 }, lodgingPerNightUsd: 360, foodPerDayUsd: 90, activitiesPerDayUsd: 80 },
    bestSeasons: ["spring", "summer", "fall", "winter"],
  },
  {
    slug: "key-west-fl",
    name: "Key West",
    region: "Florida Keys",
    state: "FL",
    lat: 24.5551, lng: -81.7800,
    tags: ["chill", "foodie", "scenic", "nightlife"],
    blurb: "End of the road — Hemingway's town, conch fritters, and the most reliable winter sun east of the Mississippi.",
    attractions: [
      { name: "Mallory Square", description: "Sunset celebration — buskers, key lime pie, and the Gulf going pink." },
      { name: "Hemingway Home", description: "Six-toed cats descended from Papa's own." },
      { name: "Dry Tortugas", description: "Seaplane to a Civil-War fort 70 miles offshore — best snorkel in the Keys." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 300, CHI: 260, LAX: 380, SFO: 420, SEA: 460 }, lodgingPerNightUsd: 320, foodPerDayUsd: 95, activitiesPerDayUsd: 60 },
    bestSeasons: ["winter", "spring"],
  },
  {
    slug: "hudson-valley-ny",
    name: "Hudson Valley",
    region: "Hudson River",
    state: "NY",
    lat: 41.7004, lng: -73.9210,
    tags: ["scenic", "foodie", "chill", "cultural"],
    blurb: "Manhattan's backyard — riverside hamlets, farm-to-table, and the country's highest concentration of art museums per acre.",
    attractions: [
      { name: "Storm King Art Center", description: "500 acres of large-scale outdoor sculpture in New Windsor." },
      { name: "Dia Beacon", description: "Former Nabisco factory, monumental minimalist art." },
      { name: "Cold Spring", description: "Walkable Main Street and the Hudson Highlands trailheads." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 0, CHI: 220, LAX: 360, SFO: 380, SEA: 400 }, lodgingPerNightUsd: 280, foodPerDayUsd: 90, activitiesPerDayUsd: 35 },
    bestSeasons: ["spring", "summer", "fall"],
  },
  {
    slug: "cape-cod-ma",
    name: "Cape Cod",
    region: "New England Coast",
    state: "MA",
    lat: 41.6688, lng: -70.2962,
    tags: ["scenic", "chill", "foodie"],
    blurb: "The Outer Cape — 40 miles of national seashore, lobster shacks, and beach towns the rest of the country has forgotten.",
    attractions: [
      { name: "Cape Cod National Seashore", description: "Marconi Beach to Race Point — protected dunes and seal colonies." },
      { name: "Provincetown", description: "Walkable end-of-Cape town: galleries, drag shows, and whale-watch boats." },
      { name: "Wellfleet Drive-In", description: "Last original-format drive-in theater on the Cape." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 220, CHI: 280, LAX: 420, SFO: 440, SEA: 440 }, lodgingPerNightUsd: 280, foodPerDayUsd: 85, activitiesPerDayUsd: 25 },
    bestSeasons: ["summer", "fall"],
  },
  {
    slug: "san-diego-ca",
    name: "San Diego",
    region: "Southern California",
    state: "CA",
    lat: 32.7157, lng: -117.1611,
    tags: ["city", "chill", "foodie", "scenic"],
    blurb: "70-degree-year-round beach city — fish tacos, surf, and the country's most underrated zoo.",
    attractions: [
      { name: "Balboa Park", description: "1,200-acre park with 17 museums and the San Diego Zoo." },
      { name: "La Jolla Cove", description: "Sea-lion cove and underwater ecological reserve for snorkeling." },
      { name: "North Park", description: "Best taco + brewery walking neighborhood." },
    ],
    typicalCostBands: { flightFromOrigin: { NYC: 320, CHI: 240, LAX: 80, SFO: 160, SEA: 220 }, lodgingPerNightUsd: 240, foodPerDayUsd: 70, activitiesPerDayUsd: 35 },
    bestSeasons: ["spring", "summer", "fall", "winter"],
  },
];
