-- Auto-generated from src/lib/seed/destinations.ts. DO NOT HAND-EDIT.
-- Regenerate with: npm run seed:sql

insert into public.destinations_seed (
  slug, name, region, state, lat, lng, tags, blurb, hero_photo_url,
  attractions, typical_cost_bands, best_seasons, max_flight_hours_from_origin
) values
  ('boston-ma', 'Boston', 'New England', 'MA', 42.3601, -71.0589, ARRAY['city', 'cultural', 'foodie']::text[], 'Walkable colonial city with serious chowder, world-class museums, and a coastline minutes from downtown.', NULL, '[{"name":"Freedom Trail","description":"2.5-mile self-guided history walk through 16 sites."},{"name":"Museum of Fine Arts","description":"One of the most comprehensive art collections in the Americas."},{"name":"North End","description":"Italian neighborhood with the city''s best red-sauce."}]'::jsonb, '{"flightFromOrigin":{"NYC":180,"CHI":240,"LAX":380,"SFO":380,"SEA":380},"lodgingPerNightUsd":220,"foodPerDayUsd":80,"activitiesPerDayUsd":30}'::jsonb, ARRAY['spring', 'summer', 'fall']::text[], NULL),
  ('charleston-sc', 'Charleston', 'Lowcountry', 'SC', 32.7765, -79.9311, ARRAY['city', 'foodie', 'cultural', 'scenic']::text[], 'Pastel Antebellum streets, oyster bars, and a food scene that punches three weight classes above its size.', NULL, '[{"name":"Rainbow Row","description":"13 restored Georgian houses on East Bay."},{"name":"Husk","description":"Lowcountry tasting menu in a Queen Anne mansion."},{"name":"Sullivan''s Island","description":"10-minute drive to wide, uncrowded beaches."}]'::jsonb, '{"flightFromOrigin":{"NYC":230,"CHI":260,"LAX":380,"SFO":410,"SEA":430},"lodgingPerNightUsd":240,"foodPerDayUsd":90,"activitiesPerDayUsd":35}'::jsonb, ARRAY['spring', 'fall']::text[], NULL),
  ('savannah-ga', 'Savannah', 'Lowcountry', 'GA', 32.0809, -81.0912, ARRAY['city', 'scenic', 'chill', 'cultural']::text[], '22 squares of moss-draped oak under a slow Southern pace — a city that feels half garden.', NULL, '[{"name":"Forsyth Park","description":"30 acres of fountains and live oaks at the historic district''s south end."},{"name":"Bonaventure Cemetery","description":"Riverside burial ground famous for Spanish moss and statuary."},{"name":"Tybee Island","description":"20 minutes east, walkable beach town with a pier and lighthouse."}]'::jsonb, '{"flightFromOrigin":{"NYC":220,"CHI":260,"LAX":400,"SFO":420,"SEA":440},"lodgingPerNightUsd":200,"foodPerDayUsd":75,"activitiesPerDayUsd":25}'::jsonb, ARRAY['spring', 'fall']::text[], NULL),
  ('new-orleans-la', 'New Orleans', 'Gulf Coast', 'LA', 29.9511, -90.0715, ARRAY['city', 'foodie', 'nightlife', 'cultural']::text[], 'Creole, jazz, beignets, and balcony shadows — the most distinctive food city in America.', NULL, '[{"name":"French Quarter","description":"Iron-laced balconies, Bourbon and Royal Streets, Café du Monde."},{"name":"Frenchmen Street","description":"Live music every night without the Bourbon-Street frenzy."},{"name":"Garden District","description":"Walking tour through Greek Revival mansions and Lafayette Cemetery No. 1."}]'::jsonb, '{"flightFromOrigin":{"NYC":220,"CHI":200,"LAX":280,"SFO":320,"SEA":380},"lodgingPerNightUsd":200,"foodPerDayUsd":95,"activitiesPerDayUsd":30}'::jsonb, ARRAY['spring', 'fall', 'winter']::text[], NULL),
  ('nashville-tn', 'Nashville', 'Mid-South', 'TN', 36.1627, -86.7816, ARRAY['city', 'nightlife', 'foodie', 'cultural']::text[], 'Honky-tonks and hot chicken, plus a younger food scene quietly rivaling the music.', NULL, '[{"name":"Country Music Hall of Fame","description":"Definitive collection of country music history."},{"name":"Hattie B''s","description":"The hot chicken benchmark — go to Charlotte Ave. before noon."},{"name":"Ryman Auditorium","description":"Original Grand Ole Opry, still hosting shows."}]'::jsonb, '{"flightFromOrigin":{"NYC":220,"CHI":180,"LAX":320,"SFO":360,"SEA":380},"lodgingPerNightUsd":230,"foodPerDayUsd":80,"activitiesPerDayUsd":35}'::jsonb, ARRAY['spring', 'fall']::text[], NULL),
  ('austin-tx', 'Austin', 'Texas Hill Country', 'TX', 30.2672, -97.7431, ARRAY['city', 'foodie', 'nightlife', 'scenic']::text[], 'Hill-country lakes, taco trailers, and live music seven nights a week.', NULL, '[{"name":"Franklin Barbecue","description":"Worth the line — at minimum once in your life."},{"name":"Barton Springs","description":"70°F spring-fed pool in Zilker Park, year-round."},{"name":"South Congress","description":"Vintage shops, food trailers, the boot store from every Austin photo."}]'::jsonb, '{"flightFromOrigin":{"NYC":260,"CHI":220,"LAX":240,"SFO":280,"SEA":320},"lodgingPerNightUsd":240,"foodPerDayUsd":75,"activitiesPerDayUsd":30}'::jsonb, ARRAY['spring', 'fall']::text[], NULL),
  ('asheville-nc', 'Asheville', 'Blue Ridge', 'NC', 35.5951, -82.5515, ARRAY['city', 'scenic', 'foodie', 'nature']::text[], 'Mountain town with America''s biggest house, a craft-brewery per capita rivaling Portland, and the Blue Ridge Parkway out the back door.', NULL, '[{"name":"Biltmore Estate","description":"America''s largest privately owned home; gardens are the move in spring."},{"name":"Blue Ridge Parkway","description":"Scenic drive immediately out of town — stop at Craggy Gardens."},{"name":"River Arts District","description":"Working-artist warehouses along the French Broad."}]'::jsonb, '{"flightFromOrigin":{"NYC":250,"CHI":240,"LAX":380,"SFO":410,"SEA":420},"lodgingPerNightUsd":220,"foodPerDayUsd":75,"activitiesPerDayUsd":35}'::jsonb, ARRAY['spring', 'fall']::text[], NULL),
  ('santa-fe-nm', 'Santa Fe', 'Southwest', 'NM', 35.687, -105.9378, ARRAY['cultural', 'scenic', 'foodie', 'chill']::text[], 'Adobe-walled art capital at 7,000 ft — green chile, Georgia O''Keeffe country, sunsets that feel staged.', NULL, '[{"name":"Canyon Road","description":"Half-mile of galleries and sculpture gardens."},{"name":"Meow Wolf","description":"Immersive art installation — book ahead."},{"name":"Tent Rocks","description":"45-minute drive; slot canyons and hoodoos in Kasha-Katuwe."}]'::jsonb, '{"flightFromOrigin":{"NYC":380,"CHI":320,"LAX":240,"SFO":260,"SEA":320},"lodgingPerNightUsd":230,"foodPerDayUsd":75,"activitiesPerDayUsd":35}'::jsonb, ARRAY['spring', 'summer', 'fall']::text[], NULL),
  ('acadia-np', 'Acadia National Park', 'Coastal Maine', 'ME', 44.3386, -68.2733, ARRAY['nature', 'scenic', 'adventure']::text[], 'Pink-granite headlands meeting the Atlantic — the only fjord on the eastern seaboard, with a side of lobster rolls.', NULL, '[{"name":"Cadillac Mountain","description":"Highest point on the US Atlantic — first US sunrise Oct–Mar."},{"name":"Jordan Pond Path","description":"3.3-mile loop with popovers at the end."},{"name":"Bar Harbor","description":"Walkable base town for the park; ferries to Schoodic Peninsula."}]'::jsonb, '{"flightFromOrigin":{"NYC":240,"CHI":320,"LAX":480,"SFO":480,"SEA":460},"lodgingPerNightUsd":240,"foodPerDayUsd":75,"activitiesPerDayUsd":25}'::jsonb, ARRAY['summer', 'fall']::text[], NULL),
  ('yellowstone-np', 'Yellowstone National Park', 'Greater Yellowstone', 'WY', 44.428, -110.5885, ARRAY['nature', 'adventure', 'scenic']::text[], 'Geysers, super-volcano calderas, and bison the size of cars — America''s first national park, still its loudest.', NULL, '[{"name":"Old Faithful + Upper Geyser Basin","description":"Highest concentration of geysers on Earth."},{"name":"Lamar Valley","description":"America''s Serengeti — wolves, bison, bears at dawn."},{"name":"Grand Prismatic Spring","description":"Largest hot spring in the US — overlook trail for the iconic shot."}]'::jsonb, '{"flightFromOrigin":{"NYC":380,"CHI":340,"LAX":340,"SFO":340,"SEA":280},"lodgingPerNightUsd":280,"foodPerDayUsd":70,"activitiesPerDayUsd":30}'::jsonb, ARRAY['summer', 'fall']::text[], NULL),
  ('yosemite-np', 'Yosemite National Park', 'Sierra Nevada', 'CA', 37.8651, -119.5383, ARRAY['nature', 'adventure', 'scenic']::text[], 'Granite cathedrals, 2,400-ft waterfalls, and giant sequoias — the most iconic vertical landscape in America.', NULL, '[{"name":"Tunnel View","description":"First arrival shot — El Cap, Half Dome, Bridalveil all in one frame."},{"name":"Glacier Point","description":"Drive-up overlook; sunset on Half Dome''s north face."},{"name":"Mist Trail","description":"Climbs alongside Vernal and Nevada Falls — wet in spring."}]'::jsonb, '{"flightFromOrigin":{"NYC":320,"CHI":280,"LAX":200,"SFO":160,"SEA":240},"lodgingPerNightUsd":260,"foodPerDayUsd":65,"activitiesPerDayUsd":25}'::jsonb, ARRAY['spring', 'summer', 'fall']::text[], NULL),
  ('zion-np', 'Zion National Park', 'Colorado Plateau', 'UT', 37.2982, -113.0263, ARRAY['nature', 'adventure', 'scenic']::text[], 'Vermillion canyon walls and the Virgin River cutting through them — slot canyons and Angels Landing.', NULL, '[{"name":"Angels Landing","description":"5-mile out-and-back; chained-cliff section is unforgettable. Permit required."},{"name":"The Narrows","description":"Wading the Virgin River through a slot canyon — rent neoprene in spring."},{"name":"Springdale","description":"Walkable gateway town with the shuttle terminus."}]'::jsonb, '{"flightFromOrigin":{"NYC":320,"CHI":260,"LAX":180,"SFO":220,"SEA":260},"lodgingPerNightUsd":250,"foodPerDayUsd":65,"activitiesPerDayUsd":30}'::jsonb, ARRAY['spring', 'fall']::text[], NULL),
  ('joshua-tree-np', 'Joshua Tree National Park', 'Mojave/Colorado Deserts', 'CA', 33.8734, -115.901, ARRAY['nature', 'scenic', 'chill', 'adventure']::text[], 'Two deserts meeting — Seussian Joshua trees, granite jumbles, dark-sky stargazing 2 hr from LA.', NULL, '[{"name":"Hidden Valley loop","description":"1-mile flat trail through monzogranite — great for first afternoon."},{"name":"Keys View","description":"Drive-up overlook of the Coachella Valley and San Andreas Fault."},{"name":"Pioneertown","description":"Old Western movie set turned cocktail town outside the park."}]'::jsonb, '{"flightFromOrigin":{"NYC":320,"CHI":260,"LAX":80,"SFO":180,"SEA":260},"lodgingPerNightUsd":200,"foodPerDayUsd":60,"activitiesPerDayUsd":20}'::jsonb, ARRAY['spring', 'fall', 'winter']::text[], NULL),
  ('smoky-mountains-np', 'Great Smoky Mountains', 'Southern Appalachians', 'TN', 35.6118, -83.4895, ARRAY['nature', 'scenic', 'chill']::text[], 'Most-visited US national park — old-growth forest, Cherokee history, and a haze that''s actually plant exhalation.', NULL, '[{"name":"Cades Cove loop","description":"11-mile drive through historic homesteads with bear sightings most mornings."},{"name":"Clingmans Dome","description":"Highest point in the park; observation tower at 6,643 ft."},{"name":"Gatlinburg","description":"Walkable gateway town for moonshine, ski lifts, and trails."}]'::jsonb, '{"flightFromOrigin":{"NYC":240,"CHI":220,"LAX":360,"SFO":380,"SEA":400},"lodgingPerNightUsd":180,"foodPerDayUsd":60,"activitiesPerDayUsd":20}'::jsonb, ARRAY['spring', 'summer', 'fall']::text[], NULL),
  ('glacier-np', 'Glacier National Park', 'Northern Rockies', 'MT', 48.7596, -113.787, ARRAY['nature', 'adventure', 'scenic']::text[], 'Crown of the Continent — turquoise lakes, hanging valleys, and Going-to-the-Sun Road carving the divide.', NULL, '[{"name":"Going-to-the-Sun Road","description":"50-mile alpine drive over Logan Pass — open mid-June to early Oct."},{"name":"Highline Trail","description":"11.8-mile ridgewalk with mountain-goat traffic."},{"name":"Lake McDonald","description":"Multicolored pebbles, big lake, west-side base for lodging."}]'::jsonb, '{"flightFromOrigin":{"NYC":360,"CHI":320,"LAX":320,"SFO":320,"SEA":220},"lodgingPerNightUsd":280,"foodPerDayUsd":70,"activitiesPerDayUsd":30}'::jsonb, ARRAY['summer']::text[], NULL),
  ('olympic-np', 'Olympic National Park', 'Pacific Northwest', 'WA', 47.8021, -123.6044, ARRAY['nature', 'scenic', 'adventure']::text[], 'Three ecosystems in one park — temperate rainforest, alpine ridge, and Pacific coastline with sea stacks.', NULL, '[{"name":"Hoh Rainforest","description":"Hall of Mosses — densest temperate rainforest in the world."},{"name":"Hurricane Ridge","description":"Drive-up subalpine views from Port Angeles."},{"name":"Rialto Beach","description":"Hike to Hole-in-the-Wall at low tide for sea-stack tide pools."}]'::jsonb, '{"flightFromOrigin":{"NYC":380,"CHI":320,"LAX":220,"SFO":220,"SEA":60},"lodgingPerNightUsd":220,"foodPerDayUsd":65,"activitiesPerDayUsd":25}'::jsonb, ARRAY['summer', 'fall']::text[], NULL),
  ('aspen-co', 'Aspen', 'Rockies', 'CO', 39.1911, -106.8175, ARRAY['scenic', 'adventure', 'foodie', 'chill']::text[], 'Four mountains, the Maroon Bells, and a downtown that''s somehow both a ski town and a Michelin destination.', NULL, '[{"name":"Maroon Bells","description":"Most-photographed peaks in North America — shuttle-only mid-summer."},{"name":"Aspen Mountain","description":"Gondola from downtown to 11,212 ft — lift-served hiking in summer."},{"name":"Wheeler Opera House","description":"1889 venue — small concerts in a perfect 500-seat hall."}]'::jsonb, '{"flightFromOrigin":{"NYC":420,"CHI":360,"LAX":280,"SFO":320,"SEA":360},"lodgingPerNightUsd":380,"foodPerDayUsd":110,"activitiesPerDayUsd":40}'::jsonb, ARRAY['summer', 'fall', 'winter']::text[], NULL),
  ('jackson-hole-wy', 'Jackson Hole', 'Greater Yellowstone', 'WY', 43.4799, -110.7624, ARRAY['scenic', 'adventure', 'nature', 'foodie']::text[], 'Teton Range out the front door, elk antler arches downtown, and the gateway to two national parks.', NULL, '[{"name":"Grand Teton National Park","description":"Schwabacher Landing at sunrise; Inspiration Point hike at Jenny Lake."},{"name":"National Elk Refuge","description":"Sleigh rides through the world''s largest elk herd Dec–Mar."},{"name":"Snake River float","description":"Half-day raft trip with the Tetons as a backdrop."}]'::jsonb, '{"flightFromOrigin":{"NYC":420,"CHI":380,"LAX":320,"SFO":340,"SEA":320},"lodgingPerNightUsd":320,"foodPerDayUsd":95,"activitiesPerDayUsd":50}'::jsonb, ARRAY['summer', 'fall', 'winter']::text[], NULL),
  ('sedona-az', 'Sedona', 'Colorado Plateau', 'AZ', 34.8697, -111.761, ARRAY['scenic', 'adventure', 'chill', 'nature']::text[], 'Red-rock buttes 2 hr north of Phoenix — vortexes, slickrock hikes, and one of the prettiest drives in America.', NULL, '[{"name":"Cathedral Rock","description":"1.2-mile out-and-back; classic Sedona postcard view."},{"name":"Oak Creek Canyon","description":"Drive AZ-89A north toward Flagstaff — switchbacks through red rock."},{"name":"Tlaquepaque Arts Village","description":"Adobe-walled gallery district along Oak Creek."}]'::jsonb, '{"flightFromOrigin":{"NYC":320,"CHI":260,"LAX":180,"SFO":220,"SEA":280},"lodgingPerNightUsd":280,"foodPerDayUsd":75,"activitiesPerDayUsd":30}'::jsonb, ARRAY['spring', 'fall']::text[], NULL),
  ('big-sur-ca', 'Big Sur', 'Central Coast', 'CA', 36.2704, -121.8081, ARRAY['scenic', 'chill', 'nature']::text[], '90 miles of cliff-and-redwood coastline along Highway 1 — the prettiest road trip on the West Coast.', NULL, '[{"name":"McWay Falls","description":"80-ft waterfall onto a beach in Julia Pfeiffer Burns SP."},{"name":"Bixby Bridge","description":"Iconic 1932 span — pull off northbound for the photo."},{"name":"Nepenthe","description":"Cliffside restaurant with a 40-mile coastline view."}]'::jsonb, '{"flightFromOrigin":{"NYC":320,"CHI":280,"LAX":160,"SFO":100,"SEA":220},"lodgingPerNightUsd":360,"foodPerDayUsd":95,"activitiesPerDayUsd":30}'::jsonb, ARRAY['spring', 'summer', 'fall']::text[], NULL),
  ('maui-hi', 'Maui', 'Hawaiian Islands', 'HI', 20.7984, -156.3319, ARRAY['scenic', 'nature', 'chill', 'adventure']::text[], 'Volcanic crater above the clouds, a 600-curve road through jungle, and beach towns on the leeward side.', NULL, '[{"name":"Haleakalā Sunrise","description":"Drive to 10,023 ft for sunrise above the clouds — reservation required."},{"name":"Road to Hana","description":"All-day cliff drive with waterfalls, pools, and black-sand beach."},{"name":"Molokini Crater","description":"Snorkel a half-submerged volcanic crater off the south shore."}]'::jsonb, '{"flightFromOrigin":{"NYC":580,"CHI":480,"LAX":320,"SFO":320,"SEA":320},"lodgingPerNightUsd":380,"foodPerDayUsd":95,"activitiesPerDayUsd":80}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter']::text[], NULL),
  ('kauai-hi', 'Kauai', 'Hawaiian Islands', 'HI', 22.0964, -159.5261, ARRAY['scenic', 'nature', 'adventure', 'chill']::text[], 'The ''Garden Isle'' — Nā Pali sea cliffs, a Grand-Canyon-of-the-Pacific, and 80% of the island unreachable by road.', NULL, '[{"name":"Nā Pali Coast","description":"Boat or helicopter tour — 17 miles of sea cliffs you cannot drive to."},{"name":"Waimea Canyon","description":"Mark Twain''s ''Grand Canyon of the Pacific'' — drive to the rim lookouts."},{"name":"Hanalei Bay","description":"Crescent bay with mountain backdrop on the north shore."}]'::jsonb, '{"flightFromOrigin":{"NYC":600,"CHI":500,"LAX":340,"SFO":340,"SEA":360},"lodgingPerNightUsd":360,"foodPerDayUsd":90,"activitiesPerDayUsd":80}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter']::text[], NULL),
  ('key-west-fl', 'Key West', 'Florida Keys', 'FL', 24.5551, -81.78, ARRAY['chill', 'foodie', 'scenic', 'nightlife']::text[], 'End of the road — Hemingway''s town, conch fritters, and the most reliable winter sun east of the Mississippi.', NULL, '[{"name":"Mallory Square","description":"Sunset celebration — buskers, key lime pie, and the Gulf going pink."},{"name":"Hemingway Home","description":"Six-toed cats descended from Papa''s own."},{"name":"Dry Tortugas","description":"Seaplane to a Civil-War fort 70 miles offshore — best snorkel in the Keys."}]'::jsonb, '{"flightFromOrigin":{"NYC":300,"CHI":260,"LAX":380,"SFO":420,"SEA":460},"lodgingPerNightUsd":320,"foodPerDayUsd":95,"activitiesPerDayUsd":60}'::jsonb, ARRAY['winter', 'spring']::text[], NULL),
  ('hudson-valley-ny', 'Hudson Valley', 'Hudson River', 'NY', 41.7004, -73.921, ARRAY['scenic', 'foodie', 'chill', 'cultural']::text[], 'Manhattan''s backyard — riverside hamlets, farm-to-table, and the country''s highest concentration of art museums per acre.', NULL, '[{"name":"Storm King Art Center","description":"500 acres of large-scale outdoor sculpture in New Windsor."},{"name":"Dia Beacon","description":"Former Nabisco factory, monumental minimalist art."},{"name":"Cold Spring","description":"Walkable Main Street and the Hudson Highlands trailheads."}]'::jsonb, '{"flightFromOrigin":{"NYC":0,"CHI":220,"LAX":360,"SFO":380,"SEA":400},"lodgingPerNightUsd":280,"foodPerDayUsd":90,"activitiesPerDayUsd":35}'::jsonb, ARRAY['spring', 'summer', 'fall']::text[], NULL),
  ('cape-cod-ma', 'Cape Cod', 'New England Coast', 'MA', 41.6688, -70.2962, ARRAY['scenic', 'chill', 'foodie']::text[], 'The Outer Cape — 40 miles of national seashore, lobster shacks, and beach towns the rest of the country has forgotten.', NULL, '[{"name":"Cape Cod National Seashore","description":"Marconi Beach to Race Point — protected dunes and seal colonies."},{"name":"Provincetown","description":"Walkable end-of-Cape town: galleries, drag shows, and whale-watch boats."},{"name":"Wellfleet Drive-In","description":"Last original-format drive-in theater on the Cape."}]'::jsonb, '{"flightFromOrigin":{"NYC":220,"CHI":280,"LAX":420,"SFO":440,"SEA":440},"lodgingPerNightUsd":280,"foodPerDayUsd":85,"activitiesPerDayUsd":25}'::jsonb, ARRAY['summer', 'fall']::text[], NULL),
  ('san-diego-ca', 'San Diego', 'Southern California', 'CA', 32.7157, -117.1611, ARRAY['city', 'chill', 'foodie', 'scenic']::text[], '70-degree-year-round beach city — fish tacos, surf, and the country''s most underrated zoo.', NULL, '[{"name":"Balboa Park","description":"1,200-acre park with 17 museums and the San Diego Zoo."},{"name":"La Jolla Cove","description":"Sea-lion cove and underwater ecological reserve for snorkeling."},{"name":"North Park","description":"Best taco + brewery walking neighborhood."}]'::jsonb, '{"flightFromOrigin":{"NYC":320,"CHI":240,"LAX":80,"SFO":160,"SEA":220},"lodgingPerNightUsd":240,"foodPerDayUsd":70,"activitiesPerDayUsd":35}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter']::text[], NULL)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  state = excluded.state,
  lat = excluded.lat,
  lng = excluded.lng,
  tags = excluded.tags,
  blurb = excluded.blurb,
  hero_photo_url = excluded.hero_photo_url,
  attractions = excluded.attractions,
  typical_cost_bands = excluded.typical_cost_bands,
  best_seasons = excluded.best_seasons,
  max_flight_hours_from_origin = excluded.max_flight_hours_from_origin;
